table Dim_Calendario
	lineageTag: c6dae7f2-33b4-421b-9020-3d6b519f0732

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1837f644-74a9-4ae2-8a76-6c77b6adc2ce
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 84b4d812-98a8-42f6-870e-debabfd2a0a7
			defaultHierarchy: LocalDateTable_a7c674c3-1581-4be5-a2f7-ad7a8d7d5711.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 037d3a9d-35ae-4f88-9b43-754fd24ed700
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 798e92a9-c315-402d-bb1a-72eff37dd596
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 1ac4448f-2c75-4018-867c-e69a26dad594
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 23dfa49f-76b6-4779-a951-e60f1a6f90fb
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 1ad78a05-4331-45fa-b7f3-81347a492e93
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\fabri\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

