table fact_Presupuestos
	lineageTag: 01d73fd1-3c7e-4dfb-982b-f2bdcb0b3297

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: 2afec4c9-6cb9-47ea-92ea-a121f8e6377d
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: string
		lineageTag: fd7b3c41-ccc0-437c-a9d4-85211ea85d2e
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 44eff5be-59a9-4942-9716-5f1bb14a111c
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: f4601514-afe3-4469-bf00-0aac7ea2d35b
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	partition fact_Presupuestos = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\fabri\Downloads\VentasVehiculos.xlsx"), null, true),
				    fact_Presupuestos_Table = Origen{[Item="fact_Presupuestos",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(fact_Presupuestos_Table,{{"periodo", Int64.Type}, {"mes", type text}, {"id_sede", Int64.Type}, {"ppto", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

